### ISSUE TITLE
Revert by second press

### ISSUE THREAD

**Issue by d-enk** [amivaleo/Hide-Unfocused#1]
For conformity with native 'hide all' behavior

**Comment by d-enk** [comment]
Reset state (forget first press) - after changing window focus, probably

**Comment by amivaleo** [comment]
Thank you for this report.
I actually considered this feature and I need some more thinking about it, since this will make the extension pretty similar to "show desktop button".
So, I might merge the two and add a button on the preference to make it work as a "show desktop button" or as "hide unfocused".

I need to think about this. 🤔

**Comment by amivaleo** [comment]
I decided to merge this extension into show-desktop-button and add a switch to it.

I will remove this repo and the hide-unfocused extension as soon as the v44 of the other lands on the website.
